import type { Metadata } from 'next';
import './globals.css';
import { Inter } from 'next/font/google';
import { ThemeProvider } from '@/components/providers/theme-provider';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

const inter = Inter({
	subsets: ['latin'],
	// Optional: define a CSS variable name for use with Tailwind CSS or CSS files
	variable: '--font-inter'
});

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${inter.variable}  antialiased`}>
				<ThemeProvider
					attribute='class'
					defaultTheme='system'
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
